# Dashboards need to be specified here
# A prow annotation will be invalid if it references a dashboard that doesn't exist
dashboards:
- name: istio_api
- name: istio_api_postsubmit
- name: istio_bots
- name: istio_bots_postsubmit
- name: istio_client-go
- name: istio_client-go_postsubmit
- name: istio_cni
- name: istio_cni_postsubmit
- name: istio_common-files
- name: istio_common-files_postsubmit
- name: istio_community
- name: istio_community_postsubmit
- name: istio_gogo-genproto
- name: istio_gogo-genproto_postsubmit
- name: istio_infrastructure
- name: istio_installer
- name: istio_installer_postsubmit
- name: istio_istio
- name: istio_istio.io
- name: istio_istio.io_postsubmit
- name: istio_istio_postsubmit
- name: istio_operator
- name: istio_operator_postsubmit
- name: istio_pkg
- name: istio_pkg_postsubmit
- name: istio_proxy
- name: istio_proxy_postsubmit
- name: istio_release-1.2_istio
- name: istio_release-1.2_istio_postsubmit
- name: istio_release-1.3_api
- name: istio_release-1.3_cni
- name: istio_release-1.3_cni_postsubmit
- name: istio_release-1.3_istio
- name: istio_release-1.3_istio.io
- name: istio_release-1.3_istio.io_postsubmit
- name: istio_release-1.3_istio_postsubmit
- name: istio_release-1.3_operator
- name: istio_release-1.3_operator_postsubmit
- name: istio_release-1.3_pkg
- name: istio_release-1.3_pkg_postsubmit
- name: istio_release-1.3_proxy
- name: istio_release-1.3_proxy_postsubmit
- name: istio_release-1.3_release

- name: istio_release-1.4_istio_postsubmit
- name: istio_release-1.4_client-go_postsubmit
- name: istio_release-1.4_cni_postsubmit
- name: istio_release-1.4_common-files_postsubmit
- name: istio_release-1.4_gogo-genproto_postsubmit
- name: istio_release-1.4_istio.io_postsubmit
- name: istio_release-1.4_operator_postsubmit
- name: istio_release-1.4_pkg_postsubmit
- name: istio_release-1.4_proxy_postsubmit
- name: istio_release-1.4_api_postsubmit
- name: istio_release-1.4_installer_postsubmit
- name: istio_release-1.4_tools_postsubmit
- name: istio_release-1.4_release-builder_postsubmit

- name: istio_release-1.4_istio
- name: istio_release-1.4_api
- name: istio_release-1.4_client-go
- name: istio_release-1.4_cni
- name: istio_release-1.4_common-files
- name: istio_release-1.4_gogo-genproto
- name: istio_release-1.4_istio.io
- name: istio_release-1.4_operator
- name: istio_release-1.4_pkg
- name: istio_release-1.4_proxy
- name: istio_release-1.4_installer
- name: istio_release-1.4_tools
- name: istio_release-1.4_release-builder

- name: istio_release-builder_postsubmit
- name: istio_release-builder
- name: istio_release-pipeline
- name: istio_test-infra
- name: istio_test-infra_postsubmit
- name: istio_tests
- name: istio_tests_postsubmit
- name: istio_tools
- name: istio_tools_postsubmit
- name: istio-gke


# Group all dashboards
dashboard_groups:
- name: istio_release-1.4
  dashboard_names:
  - istio_release-1.4_istio_postsubmit
  - istio_release-1.4_client-go_postsubmit
  - istio_release-1.4_cni_postsubmit
  - istio_release-1.4_common-files_postsubmit
  - istio_release-1.4_gogo-genproto_postsubmit
  - istio_release-1.4_istio.io_postsubmit
  - istio_release-1.4_operator_postsubmit
  - istio_release-1.4_pkg_postsubmit
  - istio_release-1.4_proxy_postsubmit
  - istio_release-1.4_api_postsubmit
  - istio_release-1.4_installer_postsubmit
  - istio_release-1.4_tools_postsubmit
  - istio_release-1.4_release-builder_postsubmit

  - istio_release-1.4_istio
  - istio_release-1.4_api
  - istio_release-1.4_client-go
  - istio_release-1.4_cni
  - istio_release-1.4_common-files
  - istio_release-1.4_gogo-genproto
  - istio_release-1.4_istio.io
  - istio_release-1.4_operator
  - istio_release-1.4_pkg
  - istio_release-1.4_proxy
  - istio_release-1.4_installer
  - istio_release-1.4_tools
  - istio_release-1.4_release-builder

- name: istio_release-1.3
  dashboard_names:
  - istio_release-1.3_istio_postsubmit
  - istio_release-1.3_cni_postsubmit
  - istio_release-1.3_istio.io_postsubmit
  - istio_release-1.3_operator_postsubmit
  - istio_release-1.3_pkg_postsubmit
  - istio_release-1.3_proxy_postsubmit

  - istio_release-1.3_istio
  - istio_release-1.3_api
  - istio_release-1.3_cni
  - istio_release-1.3_istio.io
  - istio_release-1.3_operator
  - istio_release-1.3_pkg
  - istio_release-1.3_proxy
  - istio_release-1.3_release


- name: istio_release-1.2
  dashboard_names:
  - istio_release-1.2_istio_postsubmit
  - istio_release-1.2_istio


- name: istio
  dashboard_names:
  - istio_istio_postsubmit
  - istio_api_postsubmit
  - istio_bots_postsubmit
  - istio_client-go_postsubmit
  - istio_cni_postsubmit
  - istio_common-files_postsubmit
  - istio_community_postsubmit
  - istio_gogo-genproto_postsubmit
  - istio_installer_postsubmit
  - istio_istio.io_postsubmit
  - istio_operator_postsubmit
  - istio_pkg_postsubmit
  - istio_proxy_postsubmit
  - istio_test-infra_postsubmit
  - istio_tests_postsubmit
  - istio_tools_postsubmit

  - istio_istio
  - istio_api
  - istio_bots
  - istio_client-go
  - istio_cni
  - istio_common-files
  - istio_community
  - istio_gogo-genproto
  - istio_infrastructure
  - istio_installer
  - istio_istio.io
  - istio_operator
  - istio_pkg
  - istio_proxy
  - istio_test-infra
  - istio_tests
  - istio_tools
  - istio-gke