org: istio
repo: api
support_release_branching: true
image: gcr.io/istio-testing/build-tools:2019-10-24T14-05-17

jobs:
  - name: build
    command: [make, presubmit]

  - name: gencheck
    command: [make, gen-check]
