org: istio
repo: api
image: gcr.io/istio-testing/build-tools:2019-10-11T13-37-52
suppress_entrypoint: true
branches:
  - master

jobs:
  - name: build
    command: [make, presubmit]

  - name: gencheck
    command: [make, gen-check]
    modifiers: [optional]
