org: istio
repo: client-go
image: gcr.io/istio-testing/build-tools:2019-09-23T14-42-58
suppress_entrypoint: true
branches:
  - master
  - release-1.3

jobs:
  - name: build
    command: [make, build]
  - name: lint
    command: [make, lint]
  - name: test
    command: [make, test]
