org: istio
repo: cni
image: gcr.io/istio-testing/istio-builder:v20190829-4edc0e70
branches:
  - release-1.3

jobs:
  - name: build
    command: [entrypoint, make, docker]

  - name: install
    command: [entrypoint, make, docker, test]

  - name: e2e
    command: [entrypoint, make, prow-e2e]
    requirements: [kind]
    repos: [istio/istio]

  - name: buildmodern
    command: [make, docker]
    image: gcr.io/istio-testing/build-tools:2019-08-31T04-48-30
    modifiers: [optional]

  - name: lintmodern
    command: [make, lint_modern]
    image: gcr.io/istio-testing/build-tools:2019-08-31T04-48-30
