org: istio
repo: cni
image: gcr.io/istio-testing/build-tools:2019-10-02T14-57-08

branches:
  - master

jobs:
  - name: build
    command: [make, docker]

  - name: install
    command: [make, docker, test]

  - name: e2e
    command: [make, e2e]
    requirements: [kind]
    repos: [istio/istio]

  - name: lint
    command: [make, lint]
