org: istio
repo: cni
image: gcr.io/istio-testing/build-tools:2019-09-29T15-31-13

branches:
  - master

jobs:
  - name: build
    command: [make, docker]

  - name: install
    command: [make, docker, test]

  - name: e2e
    command: [make, prow-e2e]
    requirements: [kind]
    repos: [istio/istio]

  - name: buildmodern
    command: [make, docker]

  - name: lintmodern
    command: [make, lint_modern]
