branches:
- release-1.4
image: gcr.io/istio-testing/build-tools:2019-10-11T13-37-52
jobs:
- command:
  - make
  - lint
  name: lint
org: istio
repo: common-files
resources:
  default:
    limits:
      cpu: "3"
      memory: 24Gi
    requests:
      cpu: 500m
      memory: 3Gi
