org: istio
repo: gogo-genproto
image: gcr.io/istio-testing/build-tools:2019-09-29T15-31-13
suppress_entrypoint: true
branches:
  - master

jobs:
  - name: build
    command: [make, build]
  - name: lint
    command: [make, lint]
