org: istio
repo: gogo-genproto
image: gcr.io/istio-testing/build-tools:2019-10-10T00-49-39
suppress_entrypoint: true
branches:
  - master

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: gencheck
    command: [make, gen-check]
