org: istio
repo: installer
image: gcr.io/istio-testing/build-tools:2019-10-10T00-49-39
suppress_entrypoint: true
branches:
  - master

jobs:
  - name: build
    command: [make, run-build]

  - name: lintmodern
    command: [make, lint_modern]

  - name: demo
    command: [entrypoint, bin/with-kind.sh, make, run-test-demo]
    requirements: [kind]
    repos: [istio/istio]

  - name: noauth
    command: [entrypoint, bin/with-kind.sh, make, run-test-noauth]
    requirements: [kind]
    repos: [istio/istio]

  - name: base
    command: [entrypoint, bin/with-kind.sh, make, run-base-reachability]
    requirements: [kind]
    repos: [istio/istio]
