org: istio
repo: installer
support_release_branching: true

jobs:
  - name: build
    command: [make, run-build]

  - name: lintmodern
    command: [make, lint_modern]

  - name: demo
    command: [entrypoint, bin/with-kind.sh, make, run-test-demo]
    requirements: [kind]
    repos: [istio/istio]

  - name: noauth
    command: [entrypoint, bin/with-kind.sh, make, run-test-noauth]
    requirements: [kind]
    repos: [istio/istio]

  - name: base
    command: [entrypoint, bin/with-kind.sh, make, run-base-reachability]
    requirements: [kind]
    repos: [istio/istio]
