org: istio
repo: installer
image: gcr.io/istio-testing/build-tools:2019-09-29T15-31-13
suppress_entrypoint: true
branches:
  - master

jobs:
  - name: build
    command: [make, run-build]

  - name: lintmodern
    command: [make, lint_modern]
