org: istio
repo: istio
image: gcr.io/istio-testing/build-tools:2019-10-07T20-19-15
branches:
  - bt

jobs:
  - name: Xrelease
    type: postsubmit
    command: [prow/release-commit.sh]
    requirements: [gcp]

  - name: Xpilot-multicluster-e2e
    command: [prow/istio-pilot-multicluster-e2e.sh]
    requirements: [gcp]
    modifiers: [optional]

  - name: Xinteg-mixer-k8s-tests
    type: postsubmit
    command: [prow/integ-suite-kind.sh, test.integration.mixer.kube]
    requirements: [kind]

  - name: Xinteg-k8s-112
    type: postsubmit
    command:
    - prow/integ-suite-kind.sh
    - --node-image
    - kindest/node:v1.12.10
    - test.integration.kube.presubmit
    requirements: [kind]
    timeout: 4h

  - name: Xinteg-k8s-113
    type: postsubmit
    command:
    - prow/integ-suite-kind.sh
    - --node-image
    - kindest/node:v1.13.10
    - test.integration.kube.presubmit
    requirements: [kind]
    timeout: 4h

  - name: Xinteg-k8s-114
    type: postsubmit
    command:
    - prow/integ-suite-kind.sh
    - --node-image
    - kindest/node:v1.14.6
    - test.integration.kube.presubmit
    requirements: [kind]
    timeout: 4h
  # TODO replace with official kindest/node image. Currently this is a custom built image of the beta
  # As 1.16 has not been official released

  - name: Xinteg-k8s-116
    type: postsubmit
    command:
    - prow/integ-suite-kind.sh
    - --node-image
    - gcr.io/istio-testing/kind-node:v1.16.0-beta.1
    - test.integration.kube.presubmit
    requirements: [kind]
    timeout: 4h

resources:
  default:
    requests:
      memory: "3Gi"
      cpu: "3000m"
    limits:
      memory: "24Gi"
      cpu: "8000m"
  lint:
    requests:
      memory: "16Gi"
      cpu: "3000m"
    limits:
      memory: "24Gi"
      cpu: "5000m"
