org: istio
repo: operator
image: gcr.io/istio-testing/build-tools:2019-10-09T20-39-13
branches:
  - master

jobs:
  - name: lint
    command: [make, lint]
    suppress_entrypoint: true

  - name: mesh
    command: [make, mesh]
    suppress_entrypoint: true

  - name: test
    command: [make, test]
    suppress_entrypoint: true

  - name: mandiff
    command: [make, mandiff]
    suppress_entrypoint: true

  - name: manifest-apply
    command: [prow/e2e_install.sh]
    requirements: [kind]
    modifiers: [optional, hidden]

  - name: gencheck
    command: [make, gen-check]
    modifiers: [optional]
    suppress_entrypoint: true

  - name: release
    type: postsubmit
    command: [make, docker.all]
    requirements: [gcp]
