org: istio
repo: pkg
image: gcr.io/istio-testing/build-tools:2019-08-31T04-48-30
branches:
  - release-1.3

jobs:
  - name: build
    command: [make, build]

  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]
