org: istio
repo: release-builder

jobs:
  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: publish
    command: [entrypoint, test/publish.sh]
    requirements: [gcp]
    resources: build

resources:
  build:
    requests:
      memory: "3Gi"
      cpu: "5000m"
    limits:
      memory: "24Gi"
      cpu: "8000m"