org: istio
repo: release-builder
support_release_branching: true
image: gcr.io/istio-testing/build-tools:2019-10-24T14-05-17

jobs:
  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: gencheck
    command: [make, gen-check]

  - name: publish
    command: [entrypoint, test/publish.sh]
    requirements: [gcp]
    resources: build

  - name: build-warning
    type: presubmit
    regex: '^release/trigger-build$'
    command: [release/build-warning.sh]
    modifiers: [optional]

  - name: publish-warning
    type: presubmit
    regex: '^release/trigger-publish$'
    command: [release/publish-warning.sh]
    modifiers: [optional]

  - name: build-release
    type: postsubmit
    regex: '^release/trigger-build$'
    command: [entrypoint, release/build.sh]
    requirements: [release]
    resources: build

  - name: publish-release
    type: postsubmit
    regex: '^release/trigger-publish$'
    command: [entrypoint, release/publish.sh]
    requirements: [release]
    resources: build

resources:
  build:
    requests:
      memory: "3Gi"
      cpu: "5000m"
    limits:
      memory: "24Gi"
      cpu: "8000m"