org: istio
repo: release-builder
image: gcr.io/istio-testing/build-tools:2019-10-05T18-10-09
suppress_entrypoint: true
branches:
  - master

jobs:
  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: publish
    command: [entrypoint, test/publish.sh]
    requirements: [gcp]
    resources: build

resources:
  build:
    requests:
      memory: "3Gi"
      cpu: "5000m"
    limits:
      memory: "24Gi"
      cpu: "8000m"