org: istio
repo: release-builder
support_release_branching: true

jobs:
  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: publish
    command: [entrypoint, test/publish.sh]
    requirements: [gcp]
    resources: build

  - name: build-warning
    type: presubmit
    regex: '^release/trigger-build$'
    command: [release/build-warning.sh]
    modifiers: [optional]

  - name: publish-warning
    type: presubmit
    regex: '^release/trigger-publish$'
    command: [release/build-warning.sh]
    modifiers: [optional]

resources:
  build:
    requests:
      memory: "3Gi"
      cpu: "5000m"
    limits:
      memory: "24Gi"
      cpu: "8000m"