org: istio
repo: release-builder
image: gcr.io/istio-testing/build-tools:2019-10-02T14-57-08
suppress_entrypoint: true
branches:
  - master

jobs:
  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: publish
    command: [entrypoint, test/publish.sh]
    modifiers: [optional]
    requirements: [gcp]
