org: istio
repo: test-infra
image: gcr.io/istio-testing/build-tools:2019-09-29T15-31-13
suppress_entrypoint: true
branches:
  - master

jobs:
  - name: lint
    command: [make, lint]
  - name: test
    command: [make, test]
  - name: check-config
    command: [make, check-config]
