org: istio
repo: test-infra

jobs:
  - name: lint
    command: [make, lint]

  - name: test
    command: [make, test]

  - name: check-config
    command: [make, check-config]

  - name: gencheck
    command: [make, gen-check]
    modifiers: [optional]
