# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - istio
  - istio-ecosystem
  - istio-releases
  trusted_org: istio

config_updater:
  maps:
    prow/config.yaml:
      name: config
    prow/plugins.yaml:
      name: plugins
    prow/cluster/jobs/**/*.yaml:
      name: job-config

slack:
  mergewarnings:
  - repos:
    - istio/test-infra
    channels:
    - test-and-release
    whitelist:
    - istio-testing

lgtm:
- repos:
  - istio
  review_acts_as_lgtm: true
- repos:
  - istio-releases/pipeline
  review_acts_as_lgtm: true
  trusted_team_for_sticky_lgtm: "Istio Hackers"
- repos:
  - istio-ecosystem/authservice
  review_acts_as_lgtm: true

approve:
- repos:
  - istio-releases/pipeline
  implicit_self_approve: true
- repos:
  - istio-ecosystem/authservice
  implicit_self_approve: true

plugins:
  istio:
  - size
  - trigger
  - wip

  istio-ecosystem:
  - size
  - trigger
  - wip

  istio-releases:
  - size
  - trigger
  - wip

  istio/test-infra:
  - assign
  - config-updater
  - golint
  - hold
  - lifecycle
  - skip
  - slackevents

  istio-releases/pipeline:
  - lifecycle
  - hold

  istio-ecosystem/authservice:
  - approve
  - assign
  - blunderbuss
  - golint
  - help
  - hold
  - lgtm
  - lifecycle
  - slackevents
  - verify-owners

external_plugins:
  istio:
  - name: needs-rebase
    events:
    - pull_request
  - name: cherrypicker
    events:
      - issue_comment
      - pull_request
  istio-releases/pipeline:
  - name: needs-rebase
    events:
    - pull_request
  istio-ecosystem/authservice:
  - name: needs-rebase
    events:
    - pull_request
